### ISSUE TITLE
Is there a benefit to using useSession versus a regular svelte store?

### ISSUE THREAD

**Issue by jamauro** [rdb/svelte-meteor-data#7]
I suppose it's that Session variables will be persisted through a hot code push and I assume svelte stores won't be. Curious if you (or others) know of other benefits?

**Comment by rdb** [comment]
Persistence through hot code reload is the main advantage I can think of.  However, the main reason I added it is to help with porting existing applications to Svelte that are already using Session variables in non-Svelte code.
