### ISSUE TITLE
Meteor user data not updated using useTracker

### ISSUE THREAD

**Issue by jaybeemind** [rdb/svelte-meteor-data#8]
Hi, I have this piece of code, which I got from the tutorial in Meteor website:

`$: currentUser = useTracker(() => Meteor.user())`

The problem is, it's not rerun when I change the user's info (or even just logging out).

But when I do this, it reruns as expected:
```
// get current user
let currentuser
$: {
  Tracker.autorun(() => (currentUser = Meteor.user()))
  console.log('user:', currentuser)
}
```

Any help with this is appreciated, thanks!

**Comment by rdb** [comment]
That should work in principle.  Do you have more code you can show, or perhaps a complete sample, so that I could try to reproduce the issue?

**Comment by jaybeemind** [comment]
Hi, when I tried using this:

```
$: currentUser = useTracker(() => Meteor.user())
...
async function getData() {
  try {
    const result = await fetch('getData', { currentUser.prop })
  }
}
....
onMount(async () => await getData() )
```

Then do some changes on user's data in another tab, it doesn't rerun.

I even tried using these code samples and was simply console logging `currentUser`, not even the console log gets called.
![image](https://user-images.githubusercontent.com/12679838/92681348-0389e480-f360-11ea-9e9e-fc51dbafb2da.png)

But this piece of code reruns on both function call and console log:
```
// get current user
let currentUser
$: Tracker.autorun(() => {
  currentUser = Meteor.user()
})
```

These are my packages/versions, if it helps:

.meteor/packages

- svelte:blaze-integration
- rdb:svelte-meteor-data
- svelte:compiler@4.0.0-beta.1!

.meteor/versions

- svelte:blaze-integration@0.4.0
- svelte:compiler@4.0.0-beta.1
- rdb:svelte-meteor-data@0.2.3

package.json

- "svelte": "^3.24.1"

also
```
"meteor": {
    "mainModule": {
      "client": "client/main.js",
      "server": "server/main.js"
    },
    "testModule": "tests/main.js",
    "nodeModules": {
      "recompile": {
        "svelte": true
      }
    }
  }
```

Thanks for this, initially I thought I wouldn't need this package since I was not using `useTracker`, but `Tracker.autorun` is not rerunning when this package is not included.

I'll probably leave it at that for now, since it's kind of minor on my part, but might be worth looking into, that's why I asked about it.
