### ISSUE TITLE
More complex example?

### ISSUE THREAD

**Issue by skandragon** [rdb/svelte-meteor-data#9]
Sorry to use an issue tracker for a question...

While I've seen several examples of simple apps using this library, I have not seen a more realistic real-world example which has multiple deeper components, where if the database is changed, all updates are propagated properly.

In my case, I'm trying to do something like the following.  Note that I have worked with Meteor a very long time ago, but not recently, and never Svelte, so there could be a learning curve.  I'm also very much a back-end engineer, and yes, I'm making a web app.  Be afraid.

I have a "planet" object which has this general shape:

```json
{
  "system": "Sol",
  "number": 3,
  "resources": [
    { "name": "iron", "quantity": 4.5, "tapped": false },
    { "name": "copper", "quantity": 3.6, "tapped": false}
  ]
}
```

I have a component which does:

```
    $: planets = useTracker(() => Planets.find({}).fetch());
```

and then uses an `{#each $planets as planet}<Planet {planet}/>{/each}` to render the list.  This works, and adding, removing, etc. make the list update properly.  However, it seems changing the entries inside of the objects does not cause any sub-components of <Planet> to re-render.  That is, it seems the change detection works one level down, but anything lower than the first component seems to not work.

In this case, <Planet> prints out planet.name, and then calls another component to render the planet.resources, one at a time, with a string provided for the one to render.  This part does not update if the values change.

Do you have an example at hand that will propagate the reactive changes through components without having to re-fetch the item from the database in each component to ensure updates are properly triggered?

The hack is to pass the planet._id, and then fetch it in each component again, which while local is fast enough, this seems wrong.

**Comment by rdb** [comment]
Hi, sorry to not have noticed this issue earlier.  Before I look closer at your use case, I have just a question, do you have the `immutable` flag set in `svelte:options`?

**Comment by skandragon** [comment]
I do not have that flag set.  With Meteor, I'm not even sure how to set it.

That said, I seem to have solved my problems.  Mostly.  Kinda.  :)

The work-around / solution is to make sure that I always refer to `$planet` in some way.  For example,

```
function foo() {
  return planet.name
}
```

If I call this function as `{foo()}` it will return what feels like a random name for a random planet.  If I rewrite this to pass in the `$planet` it works properly.

**Comment by rdb** [comment]
I think if you were to use destructuring syntax or accessed it via its properties it would work:
```svelte
{#each $planets as planet}<Planet {...planet}/>{/each}
```
or
```svelte
{#each $planets as planet}<Planet name={planet.name}/>{/each}
```

The way I recommend doing it is to just pass in the identifier:
```svelte
<script>
$: planets = Planets.find({}, {fields: {_id: 1}});
</script>
{#each $planets as planet (planet._id)}<Planet id={planet._id}/>{/each}
```
And then in the Planet component, do something like this:
```
export let id;
$: planet = useTracker(() => Planets.findOne(id));
```
That makes sure that you have a reactive `$planet` store available in the Planet component that does update when its properties change.

**Comment by skandragon** [comment]
Sounds good, thanks!
